[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://szthaaaknsepatlcvrn.supabase.co/functions/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/send-booking-confirmation"
  to = "https://szthaaaknsepatlcvrn.supabase.co/functions/v1/send-booking-confirmation"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build.environment]
  NODE_VERSION = "18"